name: Deploy to Production Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH and known_hosts
      env:
        SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
        echo "$DEPLOY_KEY" > deploy_key
        chmod 600 deploy_key

    - name: Deploy to server
      env:
        DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        HOST: sv14731.xserver.jp
        USER: txtmemo
        PORT: 10022
      run: |
        rsync -avz -e "ssh -p $PORT -i deploy_key" ./ $USER@$HOST:/home/txtmemo/txtmemo-sub.com/Todo
        rm -f deploy_key